// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PictureSpider.LocalSingleFile;

#nullable disable

namespace PictureSpider.Migrations.DatabaseMigrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PictureSpider.LocalSingleFile.Illust", b =>
                {
                    b.Property<string>("path")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime");

                    b.Property<bool>("fav")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("sub_path")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.HasKey("path");

                    b.ToTable("Waited");
                });
#pragma warning restore 612, 618
        }
    }
}
