// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PictureSpider.LocalSingleFile;

#nullable disable

namespace PictureSpider.Migrations.DatabaseMigrations
{
    [DbContext(typeof(Database))]
    [Migration("20231229204022_lsf_dev4")]
    partial class lsf_dev4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PictureSpider.LocalSingleFile.Illust", b =>
                {
                    b.Property<string>("path")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime");

                    b.Property<bool>("fav")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("path");

                    b.ToTable("Waited");
                });
#pragma warning restore 612, 618
        }
    }
}
